# Generated by Django 4.1.4 on 2026-01-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
